export const env = {
  REACT_APP_EMAILJS_USERID: process.env.REACT_APP_EMAILJS_USERID,
  REACT_APP_EMAILJS_INQUIRY_TEMPLATEID:process.env.REACT_APP_EMAILJS_INQUIRY_TEMPLATEID,
  REACT_APP_EMAILJS_REPLY_TEMPLATEID:process.env.REACT_APP_EMAILJS_REPLY_TEMPLATEID,
  REACT_APP_EMAILJS_SERVICEID: process.env.REACT_APP_EMAILJS_SERVICEID
};